/**
 * Copyright (C) 2014 - present by OpenGamma Inc. and the OpenGamma group of companies
 *
 * Please see distribution for license.
 */
package com.opengamma.master.config.impl;

import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import java.util.NoSuchElementException;
import java.util.Set;

import org.joda.beans.Bean;
import org.joda.beans.BeanDefinition;
import org.joda.beans.ImmutableBean;
import org.joda.beans.ImmutableConstructor;
import org.joda.beans.JodaBeanUtils;
import org.joda.beans.MetaProperty;
import org.joda.beans.Property;
import org.joda.beans.PropertyDefinition;
import org.joda.beans.impl.direct.DirectFieldsBeanBuilder;
import org.joda.beans.impl.direct.DirectMetaBean;
import org.joda.beans.impl.direct.DirectMetaProperty;
import org.joda.beans.impl.direct.DirectMetaPropertyMap;

import com.google.common.collect.ImmutableList;
import com.opengamma.master.RemoteComponentInfo;
import com.opengamma.util.ArgumentChecker;

/**
 *
 */
@BeanDefinition
public final class RemoteComponentsInfo implements ImmutableBean {

  @PropertyDefinition(validate = "notNull")
  private final ImmutableList<RemoteComponentInfo<?>> components;

  @ImmutableConstructor
  public RemoteComponentsInfo(Iterable<RemoteComponentInfo<?>> components) {
    this.components = ImmutableList.copyOf(ArgumentChecker.notNull(components, "components"));
  }

  //------------------------- AUTOGENERATED START -------------------------
  ///CLOVER:OFF
  /**
   * The meta-bean for {@code RemoteComponentsInfo}.
   * @return the meta-bean, not null
   */
  public static RemoteComponentsInfo.Meta meta() {
    return RemoteComponentsInfo.Meta.INSTANCE;
  }

  static {
    JodaBeanUtils.registerMetaBean(RemoteComponentsInfo.Meta.INSTANCE);
  }

  /**
   * Returns a builder used to create an instance of the bean.
   * @return the builder, not null
   */
  public static RemoteComponentsInfo.Builder builder() {
    return new RemoteComponentsInfo.Builder();
  }

  @Override
  public RemoteComponentsInfo.Meta metaBean() {
    return RemoteComponentsInfo.Meta.INSTANCE;
  }

  @Override
  public <R> Property<R> property(String propertyName) {
    return metaBean().<R>metaProperty(propertyName).createProperty(this);
  }

  @Override
  public Set<String> propertyNames() {
    return metaBean().metaPropertyMap().keySet();
  }

  //-----------------------------------------------------------------------
  /**
   * Gets the components.
   * @return the value of the property, not null
   */
  public ImmutableList<RemoteComponentInfo<?>> getComponents() {
    return components;
  }

  //-----------------------------------------------------------------------
  /**
   * Returns a builder that allows this bean to be mutated.
   * @return the mutable builder, not null
   */
  public Builder toBuilder() {
    return new Builder(this);
  }

  @Override
  public RemoteComponentsInfo clone() {
    return this;
  }

  @Override
  public boolean equals(Object obj) {
    if (obj == this) {
      return true;
    }
    if (obj != null && obj.getClass() == this.getClass()) {
      RemoteComponentsInfo other = (RemoteComponentsInfo) obj;
      return JodaBeanUtils.equal(getComponents(), other.getComponents());
    }
    return false;
  }

  @Override
  public int hashCode() {
    int hash = getClass().hashCode();
    hash += hash * 31 + JodaBeanUtils.hashCode(getComponents());
    return hash;
  }

  @Override
  public String toString() {
    StringBuilder buf = new StringBuilder(64);
    buf.append("RemoteComponentsInfo{");
    buf.append("components").append('=').append(JodaBeanUtils.toString(getComponents()));
    buf.append('}');
    return buf.toString();
  }

  //-----------------------------------------------------------------------
  /**
   * The meta-bean for {@code RemoteComponentsInfo}.
   */
  public static final class Meta extends DirectMetaBean {
    /**
     * The singleton instance of the meta-bean.
     */
    static final Meta INSTANCE = new Meta();

    /**
     * The meta-property for the {@code components} property.
     */
    @SuppressWarnings({"unchecked", "rawtypes" })
    private final MetaProperty<ImmutableList<RemoteComponentInfo<?>>> _components = DirectMetaProperty.ofImmutable(
        this, "components", RemoteComponentsInfo.class, (Class) ImmutableList.class);
    /**
     * The meta-properties.
     */
    private final Map<String, MetaProperty<?>> _metaPropertyMap$ = new DirectMetaPropertyMap(
        this, null,
        "components");

    /**
     * Restricted constructor.
     */
    private Meta() {
    }

    @Override
    protected MetaProperty<?> metaPropertyGet(String propertyName) {
      switch (propertyName.hashCode()) {
        case -447446250:  // components
          return _components;
      }
      return super.metaPropertyGet(propertyName);
    }

    @Override
    public RemoteComponentsInfo.Builder builder() {
      return new RemoteComponentsInfo.Builder();
    }

    @Override
    public Class<? extends RemoteComponentsInfo> beanType() {
      return RemoteComponentsInfo.class;
    }

    @Override
    public Map<String, MetaProperty<?>> metaPropertyMap() {
      return _metaPropertyMap$;
    }

    //-----------------------------------------------------------------------
    /**
     * The meta-property for the {@code components} property.
     * @return the meta-property, not null
     */
    public MetaProperty<ImmutableList<RemoteComponentInfo<?>>> components() {
      return _components;
    }

    //-----------------------------------------------------------------------
    @Override
    protected Object propertyGet(Bean bean, String propertyName, boolean quiet) {
      switch (propertyName.hashCode()) {
        case -447446250:  // components
          return ((RemoteComponentsInfo) bean).getComponents();
      }
      return super.propertyGet(bean, propertyName, quiet);
    }

    @Override
    protected void propertySet(Bean bean, String propertyName, Object newValue, boolean quiet) {
      metaProperty(propertyName);
      if (quiet) {
        return;
      }
      throw new UnsupportedOperationException("Property cannot be written: " + propertyName);
    }

  }

  //-----------------------------------------------------------------------
  /**
   * The bean-builder for {@code RemoteComponentsInfo}.
   */
  public static final class Builder extends DirectFieldsBeanBuilder<RemoteComponentsInfo> {

    private List<RemoteComponentInfo<?>> components = new ArrayList<RemoteComponentInfo<?>>();

    /**
     * Restricted constructor.
     */
    private Builder() {
    }

    /**
     * Restricted copy constructor.
     * @param beanToCopy  the bean to copy from, not null
     */
    private Builder(RemoteComponentsInfo beanToCopy) {
      this.components = new ArrayList<RemoteComponentInfo<?>>(beanToCopy.getComponents());
    }

    //-----------------------------------------------------------------------
    @Override
    public Object get(String propertyName) {
      switch (propertyName.hashCode()) {
        case -447446250:  // components
          return components;
        default:
          throw new NoSuchElementException("Unknown property: " + propertyName);
      }
    }

    @SuppressWarnings("unchecked")
    @Override
    public Builder set(String propertyName, Object newValue) {
      switch (propertyName.hashCode()) {
        case -447446250:  // components
          this.components = (List<RemoteComponentInfo<?>>) newValue;
          break;
        default:
          throw new NoSuchElementException("Unknown property: " + propertyName);
      }
      return this;
    }

    @Override
    public Builder set(MetaProperty<?> property, Object value) {
      super.set(property, value);
      return this;
    }

    @Override
    public Builder setString(String propertyName, String value) {
      setString(meta().metaProperty(propertyName), value);
      return this;
    }

    @Override
    public Builder setString(MetaProperty<?> property, String value) {
      super.set(property, value);
      return this;
    }

    @Override
    public Builder setAll(Map<String, ? extends Object> propertyValueMap) {
      super.setAll(propertyValueMap);
      return this;
    }

    @Override
    public RemoteComponentsInfo build() {
      return new RemoteComponentsInfo(
          components);
    }

    //-----------------------------------------------------------------------
    /**
     * Sets the {@code components} property in the builder.
     * @param components  the new value, not null
     * @return this, for chaining, not null
     */
    public Builder components(List<RemoteComponentInfo<?>> components) {
      JodaBeanUtils.notNull(components, "components");
      this.components = components;
      return this;
    }

    //-----------------------------------------------------------------------
    @Override
    public String toString() {
      StringBuilder buf = new StringBuilder(64);
      buf.append("RemoteComponentsInfo.Builder{");
      buf.append("components").append('=').append(JodaBeanUtils.toString(components));
      buf.append('}');
      return buf.toString();
    }

  }

  ///CLOVER:ON
  //-------------------------- AUTOGENERATED END --------------------------
}
