/**
 * Copyright (C) 2011 - present by OpenGamma Inc. and the OpenGamma group of companies
 *
 * Please see distribution for license.
 */
package com.opengamma.analytics.financial.instrument.index;

import org.apache.commons.lang.ObjectUtils;
import org.threeten.bp.ZonedDateTime;

import com.opengamma.analytics.financial.instrument.annuity.AnnuityDefinition;
import com.opengamma.analytics.financial.instrument.payment.CouponDefinition;
import com.opengamma.analytics.financial.instrument.swap.SwapDefinition;
import com.opengamma.util.ArgumentChecker;

/**
 * Generator (or template) for OIS.
 */
public class GeneratorSwapONCompoundingIbor extends GeneratorInstrument<GeneratorAttributeIROTC> {
  
  /**
   * The overnight leg generator. Not null.
   */
  private final GeneratorLegONCompounding _onLegGenerator;
  
  /**
   * The second Ibor leg generator. Not null.
   */
  private final GeneratorLegIbor _iborLegGenerator;

  
  /**
   * Constructor from two legs.
   * @param name The generator name.
   * @param onLegGenerator The Ibor leg generator.
   * @param iborLegGenerator The Ibor leg generator.
   */
  public GeneratorSwapONCompoundingIbor(final String name, final GeneratorLegONCompounding onLegGenerator, final GeneratorLegIbor iborLegGenerator) {
     super(name);
    ArgumentChecker.notNull(onLegGenerator, "overnight leg generator");
    ArgumentChecker.notNull(iborLegGenerator, "ibor leg generator");
    _onLegGenerator = onLegGenerator;
    _iborLegGenerator = iborLegGenerator;
  }


  /**
   * Returns the swap generator overnight leg.
   * @return The generator.
   */
  public GeneratorLegONCompounding getONLegGenerator() {
    return _onLegGenerator;
  }

   /**
    * Returns the swap generator for the Ibor leg.
    * @return The generator.
    */
  public GeneratorLegIbor getSecondIborLegGenerator() {
    return _iborLegGenerator;
  }
  
  /**
   * {@inheritDoc}
   * Swap with each leg generated by the respective leg generators. The spread is on the first leg, which is a payer leg.
   */
  @Override
  public SwapDefinition generateInstrument(final ZonedDateTime tradeDate, final double spread, final double notional, final GeneratorAttributeIROTC attribute) {
    ArgumentChecker.notNull(tradeDate, "Reference date");
    ArgumentChecker.notNull(attribute, "Attributes");
    final AnnuityDefinition<? extends CouponDefinition> iborLeg1 = _onLegGenerator.generateInstrument(tradeDate, spread, notional, attribute, true);
    final AnnuityDefinition<? extends CouponDefinition> iborLeg2 = _iborLegGenerator.generateInstrument(tradeDate, notional, attribute, false);
    return new SwapDefinition(iborLeg1, iborLeg2);
  }

  @Override
  public int hashCode() {
    final int prime = 31;
    int result = super.hashCode();
    result = prime * result + _onLegGenerator.hashCode();
    result = prime * result + _iborLegGenerator.hashCode();
    return result;
  }

  @Override
  public boolean equals(Object obj) {
    if (this == obj) {
      return true;
    }
    if (!super.equals(obj)) {
      return false;
    }
    if (getClass() != obj.getClass()) {
      return false;
    }
    GeneratorSwapONCompoundingIbor other = (GeneratorSwapONCompoundingIbor) obj;
    if (!ObjectUtils.equals(_onLegGenerator, other._onLegGenerator)) {
      return false;
    }
    if (!ObjectUtils.equals(_iborLegGenerator, other._iborLegGenerator)) {
      return false;
    }
    return true;
  }

}
