/**
 * Copyright (C) 2011 - present by OpenGamma Inc. and the OpenGamma group of companies
 *
 * Please see distribution for license.
 */
package com.opengamma.analytics.financial.instrument.index;

import org.apache.commons.lang.ObjectUtils;
import org.threeten.bp.ZonedDateTime;

import com.opengamma.analytics.financial.instrument.annuity.AnnuityCouponFixedDefinition;
import com.opengamma.analytics.financial.instrument.annuity.AnnuityDefinition;
import com.opengamma.analytics.financial.instrument.payment.CouponDefinition;
import com.opengamma.analytics.financial.instrument.swap.SwapDefinition;
import com.opengamma.util.ArgumentChecker;

/**
 * Generator (or template) for OIS.
 */
public class GeneratorSwapFixedONCompounding extends GeneratorInstrument<GeneratorAttributeIROTC> {

  /**
   * The fixed leg generator. Not null.
   */
  private final GeneratorLegFixed _fixedLegGenerator;
  /**
   * The overnight leg generator. Not null.
   */
  private final GeneratorLegONCompounding _onLegGenerator;
  
 /**
  * Constructor from two legs.
  * @param name The generator name.
  * @param fixedLegGenerator The fixed leg generator.
  * @param onLegGenerator The Ibor leg generator.
  */
  public GeneratorSwapFixedONCompounding(final String name, final GeneratorLegFixed fixedLegGenerator, final GeneratorLegONCompounding onLegGenerator) {
    super(name);
    ArgumentChecker.notNull(fixedLegGenerator, "fixed leg generator");
    ArgumentChecker.notNull(onLegGenerator, "overnight leg generator");
    _fixedLegGenerator = fixedLegGenerator;
    _onLegGenerator = onLegGenerator;
  }

 /**
  * Returns the swap generator fixed leg.
  * @return The generator.
  */
  public GeneratorLegFixed getFixedLegGenerator() {
    return _fixedLegGenerator;
  }

 /**
  * Returns the swap generator overnight leg.
  * @return The generator.
  */
  public GeneratorLegONCompounding getONLegGenerator() {
    return _onLegGenerator;
  }
  
  /**
   * {@inheritDoc}
   * Payer swap with each leg generated by the respective leg generators.
   */
  @Override
  public SwapDefinition generateInstrument(final ZonedDateTime date, final double rate, final double notional, final GeneratorAttributeIROTC attribute) {
    ArgumentChecker.notNull(date, "Reference date");
    ArgumentChecker.notNull(attribute, "Attributes");
    final AnnuityCouponFixedDefinition fixedLeg = _fixedLegGenerator.generateInstrument(date, rate, notional, attribute, true);
    final AnnuityDefinition<? extends CouponDefinition> onLeg = _onLegGenerator.generateInstrument(date, notional, attribute, false);
    return new SwapDefinition(fixedLeg, onLeg);
  }
  
  @Override
  public int hashCode() {
    final int prime = 31;
    int result = super.hashCode();
    result = prime * result +  _fixedLegGenerator.hashCode();
    result = prime * result + _onLegGenerator.hashCode();
    return result;
  }

  @Override
  public boolean equals(Object obj) {
    if (this == obj) {
      return true;
    }
    if (!super.equals(obj)) {
      return false;
    }
    if (getClass() != obj.getClass()) {
      return false;
    }
    GeneratorSwapFixedONCompounding other = (GeneratorSwapFixedONCompounding) obj;
    if (!ObjectUtils.equals(_fixedLegGenerator, other._fixedLegGenerator)) {
      return false;
    }
    if (!ObjectUtils.equals(_onLegGenerator, other._onLegGenerator)) {
      return false;
    }
    return true;
  }
  

}
