/**
 * Copyright (C) 2011 - present by OpenGamma Inc. and the OpenGamma group of companies
 *
 * Please see distribution for license.
 */
package com.opengamma.analytics.financial.instrument.index;

import org.apache.commons.lang.ObjectUtils;
import org.threeten.bp.ZonedDateTime;

import com.opengamma.analytics.financial.instrument.annuity.AnnuityDefinition;
import com.opengamma.analytics.financial.instrument.payment.CouponDefinition;
import com.opengamma.analytics.financial.instrument.swap.SwapDefinition;
import com.opengamma.util.ArgumentChecker;

/**
 * Class with the description of swap characteristics.
 */
public class GeneratorSwapIborIbor extends GeneratorInstrument<GeneratorAttributeIROTC> {

  /**
   * The first Ibot  leg generator. Not null.
   */
  private final GeneratorLegIbor _iborLegGenerator1;
  /**
   * The second Ibor leg generator. Not null.
   */
  private final GeneratorLegIbor _iborLegGenerator2;
  
 /**
  * Constructor from two legs.
  * @param name The generator name.
  * @param iborLegGenerator1 The first Ibor leg generator.
  * @param iborLegGenerator2 The second Ibor leg generator.
  */
  public GeneratorSwapIborIbor(final String name, final GeneratorLegIbor iborLegGenerator1, final GeneratorLegIbor iborLegGenerator2) {
    super(name);
    ArgumentChecker.notNull(iborLegGenerator1, "first ibor leg generator");
    ArgumentChecker.notNull(iborLegGenerator2, "second ibor leg generator");
    _iborLegGenerator1 = iborLegGenerator1;
    _iborLegGenerator2 = iborLegGenerator2;
  }

 /**
  * Returns the swap generator for the first Ibor leg.
  * @return The generator.
  */
  public GeneratorLegIbor getFirstIborLegGenerator() {
    return _iborLegGenerator1;
  }

 /**
  * Returns the swap generator for the second Ibor leg.
  * @return The generator.
  */
  public GeneratorLegIbor getSecondIborLegGenerator() {
    return _iborLegGenerator2;
  }
  
  /**
   * {@inheritDoc}
   * Swap with each leg generated by the respective leg generators. The spread is on the first leg, which is a payer leg.
   */
  @Override
  public SwapDefinition generateInstrument(final ZonedDateTime tradeDate, final double spread, final double notional, final GeneratorAttributeIROTC attribute) {
    ArgumentChecker.notNull(tradeDate, "Reference date");
    ArgumentChecker.notNull(attribute, "Attributes");
    final AnnuityDefinition<? extends CouponDefinition> iborLeg1 = _iborLegGenerator1.generateInstrument(tradeDate, spread, notional, attribute, true);
    final AnnuityDefinition<? extends CouponDefinition> iborLeg2 = _iborLegGenerator2.generateInstrument(tradeDate, notional, attribute, false);
    return new SwapDefinition(iborLeg1, iborLeg2);
  }

  @Override
  public int hashCode() {
    final int prime = 31;
    int result = super.hashCode();
    result = prime * result + _iborLegGenerator1.hashCode();
    result = prime * result + _iborLegGenerator2.hashCode();
    return result;
  }

  @Override
  public boolean equals(Object obj) {
    if (this == obj) {
      return true;
    }
    if (!super.equals(obj)) {
      return false;
    }
    if (getClass() != obj.getClass()) {
      return false;
    }
    GeneratorSwapIborIbor other = (GeneratorSwapIborIbor) obj;
    if (!ObjectUtils.equals(_iborLegGenerator1, other._iborLegGenerator1)) {
      return false;
    }
    if (!ObjectUtils.equals(_iborLegGenerator2, other._iborLegGenerator2)) {
      return false;
    }
    return true;
  }

}
